version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - FLASK_APP=app.main
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=newsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 